import argparse
import csv
from collections import Counter, deque
from dataclasses import dataclass
from typing import Deque, Dict, List, Tuple


STATE_ON = "ON"
STATE_OFF = "OFF"
STATE_UNCERTAIN = "UNCERTAIN"
VALID_STATES = {STATE_ON, STATE_OFF, STATE_UNCERTAIN}


@dataclass
class SeriesMetrics:
    transitions_all: int
    transitions_on_off: int
    flip_rate_per_min: float
    on_ratio_known: float
    uncertain_ratio: float


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Analyze raw/stable hand-on-wheel state CSV from hand_on_wheel.py"
    )
    p.add_argument(
        "--csv",
        required=True,
        help="Path to state CSV generated by hand_on_wheel.py --state-csv",
    )
    p.add_argument(
        "--sweep-windows",
        default="",
        help=(
            "Comma-separated window seconds to recompute stable state from raw state, "
            "e.g. '0,3,5,30'."
        ),
    )
    p.add_argument(
        "--sweep-out-csv",
        default="",
        help="Optional output CSV for sweep table.",
    )
    return p.parse_args()


def parse_binary_to_state(v: str) -> str:
    x = int(v)
    if x == 1:
        return STATE_ON
    if x == 0:
        return STATE_OFF
    return STATE_UNCERTAIN


def parse_state_text(v: str) -> str:
    t = (v or "").strip().upper()
    if t in VALID_STATES:
        return t
    raise ValueError(f"Unknown state '{v}'")


def load_rows(path: str) -> Tuple[List[float], List[str], List[str]]:
    times: List[float] = []
    raw: List[str] = []
    stable: List[str] = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        fields = set(reader.fieldnames or [])
        if "time_sec" not in fields:
            raise ValueError("CSV missing required column: time_sec")
        has_text_state = {"raw_state", "stable_state"}.issubset(fields)
        has_binary_state = {"raw_hand_on_wheel", "stable_hand_on_wheel"}.issubset(fields)
        if not has_text_state and not has_binary_state:
            raise ValueError(
                "CSV must contain either raw/stable_state or raw/stable_hand_on_wheel columns"
            )
        for r in reader:
            times.append(float(r["time_sec"]))
            if has_text_state:
                raw.append(parse_state_text(r["raw_state"]))
                stable.append(parse_state_text(r["stable_state"]))
            else:
                raw.append(parse_binary_to_state(r["raw_hand_on_wheel"]))
                stable.append(parse_binary_to_state(r["stable_hand_on_wheel"]))
    if not times:
        raise ValueError("CSV has no rows")
    return times, raw, stable


def compute_metrics(times: List[float], states: List[str]) -> SeriesMetrics:
    transitions_all = sum(1 for i in range(1, len(states)) if states[i] != states[i - 1])
    transitions_on_off = 0
    for i in range(1, len(states)):
        a, b = states[i - 1], states[i]
        if a != b and {a, b}.issubset({STATE_ON, STATE_OFF}):
            transitions_on_off += 1
    duration = max(1e-9, times[-1] - times[0])
    flip_rate_per_min = transitions_on_off / (duration / 60.0)

    known = [s for s in states if s in {STATE_ON, STATE_OFF}]
    if known:
        on_ratio_known = sum(1 for s in known if s == STATE_ON) / float(len(known))
    else:
        on_ratio_known = 0.0
    uncertain_ratio = sum(1 for s in states if s == STATE_UNCERTAIN) / float(len(states))
    return SeriesMetrics(
        transitions_all=transitions_all,
        transitions_on_off=transitions_on_off,
        flip_rate_per_min=flip_rate_per_min,
        on_ratio_known=on_ratio_known,
        uncertain_ratio=uncertain_ratio,
    )


def extract_transition_times(times: List[float], states: List[str], target_state: str) -> List[float]:
    out: List[float] = []
    for i in range(1, len(states)):
        if states[i - 1] != states[i] and states[i] == target_state:
            out.append(times[i])
    return out


def estimate_transition_lag(
    raw_times: List[float], stable_times: List[float], max_search_sec: float = 120.0
) -> Tuple[float, int]:
    """Average lag: for each stable transition, find nearest previous raw transition."""
    if not raw_times or not stable_times:
        return 0.0, 0
    lags: List[float] = []
    j = 0
    for t_stable in stable_times:
        while j + 1 < len(raw_times) and raw_times[j + 1] <= t_stable:
            j += 1
        t_raw = raw_times[j] if raw_times[j] <= t_stable else None
        if t_raw is None:
            continue
        lag = t_stable - t_raw
        if 0.0 <= lag <= max_search_sec:
            lags.append(lag)
    if not lags:
        return 0.0, 0
    return sum(lags) / len(lags), len(lags)


def vote_states(window: Deque[Tuple[float, str]], previous_state: str) -> str:
    if not window:
        return previous_state
    counts = Counter(state for _, state in window)
    max_count = max(counts.values())
    candidates = [k for k, v in counts.items() if v == max_count]
    if len(candidates) == 1:
        return candidates[0]
    if previous_state in candidates:
        return previous_state
    for s in (STATE_ON, STATE_OFF, STATE_UNCERTAIN):
        if s in candidates:
            return s
    return previous_state


def recompute_stable_states(times: List[float], raw_states: List[str], window_sec: float) -> List[str]:
    if window_sec <= 0:
        return list(raw_states)
    out: List[str] = []
    window: Deque[Tuple[float, str]] = deque()
    prev = raw_states[0] if raw_states else STATE_OFF
    for t, s in zip(times, raw_states):
        window.append((t, s))
        cutoff = t - window_sec
        while window and window[0][0] < cutoff:
            window.popleft()
        cur = vote_states(window, prev)
        out.append(cur)
        prev = cur
    return out


def parse_window_list(text: str) -> List[float]:
    out: List[float] = []
    for chunk in (text or "").split(","):
        c = chunk.strip()
        if not c:
            continue
        out.append(float(c))
    return out


def print_sweep_table(
    times: List[float], raw_states: List[str], windows: List[float], out_csv: str
) -> None:
    rows: List[Dict[str, str]] = []
    raw_m = compute_metrics(times, raw_states)
    for w in windows:
        stable = recompute_stable_states(times, raw_states, w)
        m = compute_metrics(times, stable)
        reduction = 0.0
        if raw_m.flip_rate_per_min > 1e-12:
            reduction = (raw_m.flip_rate_per_min - m.flip_rate_per_min) / raw_m.flip_rate_per_min
        rows.append(
            {
                "window_sec": f"{w:.1f}",
                "flip_rate_per_min": f"{m.flip_rate_per_min:.3f}",
                "flip_reduction_pct_vs_raw": f"{reduction * 100.0:.2f}",
                "transitions_on_off": str(m.transitions_on_off),
                "transitions_all": str(m.transitions_all),
                "uncertain_ratio": f"{m.uncertain_ratio:.3f}",
                "on_ratio_known": f"{m.on_ratio_known:.3f}",
            }
        )

    print("")
    print("=== Window Sweep (from raw_state) ===")
    print("| window_sec | flip_rate_per_min | flip_reduction_pct_vs_raw | transitions_on_off | transitions_all | uncertain_ratio | on_ratio_known |")
    print("|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        print(
            f"| {r['window_sec']} | {r['flip_rate_per_min']} | {r['flip_reduction_pct_vs_raw']} | "
            f"{r['transitions_on_off']} | {r['transitions_all']} | {r['uncertain_ratio']} | {r['on_ratio_known']} |"
        )

    if out_csv:
        with open(out_csv, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(
                f,
                fieldnames=[
                    "window_sec",
                    "flip_rate_per_min",
                    "flip_reduction_pct_vs_raw",
                    "transitions_on_off",
                    "transitions_all",
                    "uncertain_ratio",
                    "on_ratio_known",
                ],
            )
            writer.writeheader()
            for r in rows:
                writer.writerow(r)
        print(f"Sweep CSV: {out_csv}")


def main() -> None:
    args = parse_args()
    times, raw, stable = load_rows(args.csv)
    raw_m = compute_metrics(times, raw)
    stable_m = compute_metrics(times, stable)

    disagreement = sum(1 for a, b in zip(raw, stable) if a != b) / float(len(raw))
    flip_reduction = 0.0
    if raw_m.flip_rate_per_min > 1e-12:
        flip_reduction = (raw_m.flip_rate_per_min - stable_m.flip_rate_per_min) / raw_m.flip_rate_per_min

    raw_on_trans = extract_transition_times(times, raw, target_state=STATE_ON)
    raw_off_trans = extract_transition_times(times, raw, target_state=STATE_OFF)
    stable_on_trans = extract_transition_times(times, stable, target_state=STATE_ON)
    stable_off_trans = extract_transition_times(times, stable, target_state=STATE_OFF)
    on_lag, on_pairs = estimate_transition_lag(raw_on_trans, stable_on_trans)
    off_lag, off_pairs = estimate_transition_lag(raw_off_trans, stable_off_trans)

    print("=== Hand-on-wheel Temporal Stability Report ===")
    print(f"CSV: {args.csv}")
    print(f"Frames: {len(times)}")
    print(f"Duration: {times[-1] - times[0]:.2f} sec")
    print("")
    print("[Raw]")
    print(f"Transitions(all): {raw_m.transitions_all}")
    print(f"Transitions(ON<->OFF): {raw_m.transitions_on_off}")
    print(f"Flip rate: {raw_m.flip_rate_per_min:.3f} per min")
    print(f"On ratio (known only): {raw_m.on_ratio_known:.3f}")
    print(f"Uncertain ratio: {raw_m.uncertain_ratio:.3f}")
    print("")
    print("[Stable]")
    print(f"Transitions(all): {stable_m.transitions_all}")
    print(f"Transitions(ON<->OFF): {stable_m.transitions_on_off}")
    print(f"Flip rate: {stable_m.flip_rate_per_min:.3f} per min")
    print(f"On ratio (known only): {stable_m.on_ratio_known:.3f}")
    print(f"Uncertain ratio: {stable_m.uncertain_ratio:.3f}")
    print("")
    print("[Comparison]")
    print(f"Disagreement ratio (raw vs stable): {disagreement:.3f}")
    print(f"Flip-rate reduction: {flip_reduction * 100.0:.2f}%")
    if on_pairs > 0:
        print(f"Avg ON transition lag: {on_lag:.3f} sec  (matched={on_pairs})")
    if off_pairs > 0:
        print(f"Avg OFF transition lag: {off_lag:.3f} sec  (matched={off_pairs})")

    windows = parse_window_list(args.sweep_windows)
    if windows:
        print_sweep_table(times, raw, windows=windows, out_csv=args.sweep_out_csv)


if __name__ == "__main__":
    main()
